
title: VALKET
image: /images/logo-header.png
email: gerovakety@abv.bg
description: Simple description
destination: docs
baseurl: "/css-advanced-2019"
url: "" 
twitter_username: gerova.ekaterina
github_username:  gerovakety

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - docs
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
